version = 1
SPDX-PackageName = "44mesh-docs"
SPDX-PackageSupplier = "docs@44mesh.net"
SPDX-PackageDownloadLocation = "https://github.com/altermundi/44mesh-docs"

[[annotations]]
path = ".gitignore"
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 AlterMundi <docs@44mesh.net>"
SPDX-License-Identifier = "CC-BY-SA-4.0"
